[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# replace STM32G031K8Ux with your chip as listed in `probe-rs chip list`
runner = "probe-rs run --chip STM32G031K8Ux"

[build]
target = "thumbv6m-none-eabi"

[profile.release]
lto = true
opt-level = "z"
incremental = false
codegen-units = 1
debug = true

[env]
DEFMT_LOG = "trace"

[unstable]
build-std = ["core"]
#build-std-features = ["panic_immediate_abort"]

